### ISSUE TITLE
Incorrect scoring logic

### ISSUE THREAD

**Issue by robby3000** [MikhaD/wordle#20] opened 2022-02-16 21:29 UTC
![Screenshot_20220216-161645_Brave](https://user-images.githubusercontent.com/30311724/154359713-2902fcef-dcd9-4790-a4d9-9142169e600a.jpg)

It is not possible to have 2 Rs, only one should be yellow. (The answer was FROZE)

**Comment by rbrignall** [comment] 2022-02-17 13:38
See issue #9 (and a related pull request)

**Comment by robby3000** [comment] 2022-02-17 19:21
Ooops shoulda seen that!

**Comment by MikhaD** [comment] 2022-02-21 07:47
duplicate of #9

**Closed by MikhaD** 2022-02-21 07:47 UTC
