### ISSUE TITLE
Keyboard letter color bug

### ISSUE THREAD

**Issue by lukeswitz** [MikhaD/wordle#21] opened 2022-02-21 09:17 UTC
If a guess uses a correct letter twice, and the second usage isn’t in the answer, the keyboard turns the letter black when reevaluating the character. Needs an or statement to check if it exists in the answer. 

Example: I input “shows” and the first two letters (s & h) turn green, but only the H will show green on the keyboard with the S being evaluated as wrong and changed back to black.

**Comment by MikhaD** [comment] 2022-02-21 11:25
Duplicate of #10

**Closed by MikhaD** 2022-02-21 11:25 UTC
